# .github/workflows/actions.yml

name: Github Actions로 작업 병렬로 실행하기
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 작업의 1단계
        run: echo "첫 번째 작업의 첫 번째 단계입니다."
      - name: 첫 번째 작업의 2단계
        run: echo "첫 번째 작업의 두 번째 단계입니다."
      - name: 두 번째 작업의 1단계
        # 실패하기
        run: |
          echo "두 번째 작업의 첫 번째 단계입니다."
          exit 1
      - name: 두 번째 작업의 2단계
        run: echo "두 번째 작업의 두 번째 단계입니다."
