name: if 조건 연습
on:
  push:
    branches:
      - develop
      - main

jobs:
  if-test:
    runs-on: ubuntu-latest
    steps:
      - name: 테스트 실행
        id: run-tests
        run: echo "성공한 경우"

      - name: 테스트 실패 알림 (예시. 슬랙 혹은 디스코드)
        if: failure() # 이전 스텝이 실패했을 때만 실행
        run: |
          echo "테스트 실패 알림을 보내는 로직을 구현"
